apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # first
spec:
  project: default
  source:
    repoURL: https://github.com/FaresMirza/repo
    targetRevision: main
    path: apps/database
  destination:
    server: https://kubernetes.default.svc
    namespace: wave-test
