apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # backend comes after database
spec:
  project: default
  source:
    repoURL: https://github.com/FaresMirza/repo  # change to your repo URL
    targetRevision: main
    path: apps/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: wave-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
